// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epgfigmjdmgwcretghrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ2ZpZ21qZG1nd2NyZXRnaHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjcwMDMsImV4cCI6MjA3MzI0MzAwM30.XibXn_eoqEz9GqBuNNiSygWSPiY5UX8et89rMetS-F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});